import type { Workflow } from "@/types/workflow";

export const mockWorkflows: Workflow[] = [
    {
        id: "w1",
        name: "Onboarding Automation",
        owner: "John Doe",
        status: "active",
        createdAt: "2025-09-01T10:00:00Z",
        updatedAt: "2025-10-01T10:00:00Z",
        tasks: 18,
        completionRate: 92,
    },
    {
        id: "w2",
        name: "Product Launch",
        owner: "Jane Smith",
        status: "paused",
        createdAt: "2025-08-10T12:00:00Z",
        updatedAt: "2025-09-20T09:00:00Z",
        tasks: 34,
        completionRate: 75,
    },
 {
    id: "1",
    name: "Customer Onboarding",
    description: "Automated customer onboarding process",
    status: "active",
    progress: 75,
    tasks: 12,
    members: 5,
    lastUpdatedLabel: "2 hours ago",
    category: "Sales",
  },
  {
    id: "2",
    name: "Content Review Pipeline",
    description: "Multi-stage content review and approval",
    status: "active",
    progress: 60,
    tasks: 8,
    members: 3,
    lastUpdatedLabel: "5 hours ago",
    category: "Marketing",
  },
  {
    id: "3",
    name: "Bug Triage Process",
    description: "Automated bug tracking and assignment",
    status: "paused",
    progress: 45,
    tasks: 15,
    members: 7,
    lastUpdatedLabel: "1 day ago",
    category: "Engineering",
  },
  {
    id: "4",
    name: "Invoice Processing",
    description: "Automated invoice review and payment",
    status: "active",
    progress: 90,
    tasks: 6,
    members: 4,
    lastUpdatedLabel: "30 mins ago",
    category: "Finance",
  },
  {
    id: "5",
    name: "HR Recruitment",
    description: "Candidate screening and interview scheduling",
    status: "completed",
    progress: 100,
    tasks: 10,
    members: 6,
    lastUpdatedLabel: "3 days ago",
    category: "HR",
  },
  {
    id: "6",
    name: "Product Launch",
    description: "End-to-end product launch workflow",
    status: "active",
    progress: 35,
    tasks: 20,
    members: 8,
    lastUpdatedLabel: "1 hour ago",
    category: "Product",
  },
];